---
variables:
  DOCKER_BUILDKIT: 1

stages:
- test
- report
- build
  
include:
- template: Security/SAST.gitlab-ci.yml

sast_report:
  stage: report
  image: registry.code.wm.edu/pcfens/sast-parser:latest
  script:
  - echo $CI_PROJECT_URL
  - wget -o=bandit.json --header "PRIVATE-TOKEN: $CI_JOB_TOKEN" https://code.wm.edu/$CI_PROJECT_PATH/-/jobs/artifacts/$CI_COMMIT_REF_NAME/raw/gl-sast-report.json?job=bandit-sast
  - ./parse-sast.py *.json > report.html
  dependencies:
  - sast
  artifacts:
    name: SAST Report
    expire_in: 1 week
    paths:
    - report.html

build_release:
  rules:
  - if: $CI_COMMIT_TAG
    when: always
  stage: build
  image: docker:latest
  services:
  - docker:dind
  script:
  - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  - docker build -t $CI_REGISTRY_IMAGE:$CI_COMMIT_TAG .
  - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  - docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_TAG

build_head:
  rules:
  - if: $CI_COMMIT_BRANCH == "master"
    when: always
  stage: build
  image: docker:latest
  services:
  - docker:dind
  script:
  - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  - docker build -t $CI_REGISTRY_IMAGE:latest .
  - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  - docker push $CI_REGISTRY_IMAGE:latest    